#!/usr/bin/env bash
# scripts/package.sh — build a release archive for orbok.
#
# Usage:
#   ./scripts/package.sh <version>
#
# Example:
#   ./scripts/package.sh 0.9.4
#
# Output (in the repository root):
#   orbok-0.9.4.tar.gz     — source archive
#   orbok-0.9.4.tar.gz.sha256  — standalone checksum file
#
# Archive structure:
#   orbok-0.9.4/           — top-level directory named after the release
#   orbok-0.9.4/Cargo.toml
#   orbok-0.9.4/crates/
#   ...
#
# Excluded from the archive:
#   target/       — build artifacts
#   .git/         — version-control history
#   Cargo.lock    — regenerated by users on first build

set -euo pipefail

# ── Argument validation ────────────────────────────────────────────────
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <version>" >&2
    exit 1
fi
VERSION="$1"
ARCHIVE="orbok-${VERSION}.tar.gz"

# ── Resolve repository root ────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PARENT_DIR="$(dirname "${REPO_ROOT}")"
REPO_NAME="$(basename "${REPO_ROOT}")"   # typically "orbok"

# ── Build archive ──────────────────────────────────────────────────────
echo "Packaging orbok-${VERSION} ..."
cd "${PARENT_DIR}"
tar czf "${ARCHIVE}" \
    --exclude="${REPO_NAME}/target" \
    --exclude="${REPO_NAME}/.git" \
    --exclude="${REPO_NAME}/Cargo.lock" \
    --transform="s|^${REPO_NAME}|orbok-${VERSION}|" \
    "${REPO_NAME}/"

mv "${ARCHIVE}" "${REPO_ROOT}/${ARCHIVE}"
cd "${REPO_ROOT}"

# ── Checksum ───────────────────────────────────────────────────────────
sha256sum "${ARCHIVE}" > "${ARCHIVE}.sha256"
echo "SHA-256: $(cat "${ARCHIVE}.sha256" | awk '{print $1}')"

# ── Summary ───────────────────────────────────────────────────────────
echo ""
echo "Created:"
echo "  ${ARCHIVE}"
echo "  ${ARCHIVE}.sha256"
echo ""
echo "Archive contents (top 5 entries):"
tar tf "${ARCHIVE}" | head -5
echo "  ..."
echo "  ($(tar tf "${ARCHIVE}" | wc -l) entries total)"
