#!/usr/bin/env bash
# scripts/package.sh — build a release archive for orbok.
#
# Usage:
#   ./scripts/package.sh <version>
#
# Example:
#   ./scripts/package.sh 0.15.0
#
# Output (in the repository root):
#   orbok-v0.15.0.tar.gz        — source archive
#   orbok-v0.15.0.tar.gz.sha256 — standalone checksum file
#
# Archive layout (flat — no parent directory):
#   ./Cargo.toml
#   ./crates/
#   ./rfcs/
#   ...
#
# Excluded from the archive:
#   target/      — build artifacts
#   .git/        — version-control history
#   Cargo.lock   — regenerated by users on first build

set -euo pipefail

# ── Argument validation ────────────────────────────────────────────────
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <version>" >&2
    exit 1
fi
VERSION="$1"
ARCHIVE="orbok-v${VERSION}.tar.gz"

# ── Resolve repository root ────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ── Build archive ──────────────────────────────────────────────────────
# Write to a tmp path first to avoid self-inclusion, then move into place.
echo "Packaging orbok-v${VERSION} ..."
TMPARCHIVE="$(mktemp /tmp/orbok-pkg-XXXXXX.tar.gz)"
tar czf "${TMPARCHIVE}" \
    --exclude='.git' \
    --exclude='target' \
    --exclude='Cargo.lock' \
    -C "${REPO_ROOT}" \
    .
mv "${TMPARCHIVE}" "${REPO_ROOT}/${ARCHIVE}"

# ── Checksum ───────────────────────────────────────────────────────────
cd "${REPO_ROOT}"
sha256sum "${ARCHIVE}" > "${ARCHIVE}.sha256"
echo "SHA-256: $(awk '{print $1}' "${ARCHIVE}.sha256")"

# ── Summary ────────────────────────────────────────────────────────────
echo ""
echo "Created:"
echo "  ${ARCHIVE}"
echo "  ${ARCHIVE}.sha256"
echo ""
echo "Archive layout (first 8 entries — flat, no parent directory):"
tar tf "${ARCHIVE}" | head -8
echo "  ..."
echo "  ($(tar tf "${ARCHIVE}" | wc -l) entries total)"
